### ISSUE TITLE
Could you make the cookie_settings configurable?

### ISSUE THREAD

**Issue by ghost** [morepath/more.itsdangerous#1]
Hi,

when working on a development server I usually do not use `https`. The cookie setting `'secure': True` prevents me from testing.
Could you make the `cookie_settings` property configurable?

Thanks
Ludwig

**Comment by href** [comment]
You kind of can already by inheriting from `IdentityPolicy`, but I see how that's a bit bothersome. However, using `App.setting` would require a separate App from which you'd have to inherit.

So it's either this (works currently):

``` python
import morepath
from more.itsdangerous import IdentityPolicy

class App(morepath.App):
    pass

class MyIdentityPolicy(IdentityPolicy):
    @property
    def cookie_settings(self):
        return {
            'max_age': self.max_age,
            'secure': False,
            'httponly': True
        }

@App.identity_policy()
def get_identity_policy():
    return MyIdentityPolicy()
```

Or this (I'd have to add this):

``` python
import morepath
from more.itsdangerous import IdentityApp

class App(morepath.App, IdentityApp): # or just App(IdentityApp), which is less explicit
    pass

@App.setting(section="more.itsdangerous", name="secure")
def setting_secure():
    return False
```

Since the second approach doesn't really impact the IdentityPolicy class (which could still be used without the IdentityApp), I'll probably implement this next week and document this properly.

That is if I don't come up with something better. I'm also thinking of offering a few preconfigured identity policies, say `DebugIdentityPolicy` and `HttpsIdentityPolicy`.

What do you think?

**Comment by href** [comment]
Another option might be something like this:

``` python
@App.identity_policy()
def get_identity_policy():
    return IdentityPolicy(secure=False, max_age=123, httponly=True)
```

I'm currently favoring this approach.

**Comment by ghost** [comment]
You're right. Looks good. 

Am 11.04.2015 17:12 schrieb Denis Krienbühl notifications@github.com:Another option might be something like this:

@App.identity_policy()
def get_identity_policy():
    return IdentityPolicy(secure=False, max_age=123, httponly=True)

I'm currently favoring this approach.

**Comment by henri-hulski** [comment]
Maybe we should have a unified way to pass settings to dentity_policies. In More . jwt auth I use 12 settings. At the moment I use a separate app and morepath settings. 
But I can change it the way you propose. 
@faassen also proposed to refactor the morepath settings mechanism. 

Either way we should find a consensus.

**Comment by href** [comment]
> Either way we should find a consensus.

That might be a good idea. Though I would suggest we discuss this in another context, since this seems to be outside the scope of this ticket.

**Comment by faassen** [comment]
Okay, I just created that context in https://github.com/morepath/morepath/issues/309

**Comment by href** [comment]
Thanks
